apiVersion: v2
type: application
name: origin-ca-issuer
version: 0.5.5
appVersion: 0.9.0
description: A Helm chart for origin-ca-issuer
home: https://github.com/cloudflare/origin-ca-issuer
maintainers:
  - name: terinjokes
keywords:
  - cert-manager
  - cloudflare
  - tls
sources:
  - https://github.com/cloudflare/origin-ca-issuer
